using System;
using System.IO;
using System.Text;
using MonsterPouch.Gameplay.Presentation;
using UnityEditor;
using UnityEngine;

/// <summary>Explicit import of the new Dummy animation sheet; existing prototypes remain intact.</summary>
public static class MonsterPouchDummyArtSetup
{
    public const string SourcePath = "Assets/art/units/local/dummy/dummy-animation-source-v1.png";
    public const string AtlasPath = "Assets/art/units/local/dummy/dummy-animation-v1.png";
    private const string CatalogPath = "Assets/Resources/MonsterPouch/UnitArt.asset";
    private static readonly int[] SourceRows = { 4, 3, 2, 1, 0, 1, 2, 3 };

    [MenuItem("Monster Pouch/Setup Dummy authored animations")]
    public static void Setup()
    {
        UnitArtCatalog catalog = AssetDatabase.LoadAssetAtPath<UnitArtCatalog>(CatalogPath);
        if (catalog == null || catalog.Get("dummy") == null)
            throw new InvalidOperationException("Run MonsterPouchArtSetup.Setup before installing the Dummy animation atlas.");
        MonsterPouchSpriteAnimationImporter.PrepareChromaSource(SourcePath, AtlasPath, new Color32(255, 0, 255, 255));
        Sprite[,] frames = MonsterPouchSpriteAnimationImporter.ImportGrid(AtlasPath, 128, 11, 5, "dummy-v1");
        UnitArt art = catalog.Get("dummy");
        art.DirectionalAnimations = new UnitDirectionalAnimation[8];
        art.IdleDirections = new Sprite[8];
        art.AttackDirections = new Sprite[8];
        art.WalkRigs = new UnitSpriteRig[8];
        for (int d = 0; d < 8; d++)
        {
            int row = SourceRows[d];
            art.DirectionalAnimations[d] = new UnitDirectionalAnimation
            {
                Idle = Sequence(frames, row, 0, 1),
                Move = Sequence(frames, row, 2, 3, 4, 3),
                Attack = Sequence(frames, row, 5, 6, 7),
                Death = Sequence(frames, row, 8, 9, 10),
                IdleFramesPerSecond = 2.5f,
                MoveFramesPerSecond = 10f,
                AttackContactFrame = 1,
                // Dummy has no asymmetric face, markings, glove or weapon to reverse.
                FlipX = d >= 5
            };
            art.IdleDirections[d] = frames[row, 0];
            art.AttackDirections[d] = frames[row, 6];
        }
        art.Portrait = frames[0, 0];
        art.ReferencePixelWidth = Mathf.Max(1, frames[0, 0].rect.width - 4);
        art.FootPivot = new Vector2(art.Portrait.pivot.x / art.Portrait.rect.width, art.Portrait.pivot.y / art.Portrait.rect.height);
        art.ProvisionalDirectionalProjection = false;
        art.SourceNotes = "New generated Dummy pixel-art poses: 5 source views (S, SE, E, NE, N), mirrored only for SW/W/NW because this faceless toy is symmetric. Idle2, Move3 plus passing reuse, Attack3 and Death3 temporal frames. Original prototype remains intact. RGB magenta export converted to a separate real-RGBA atlas by explicit Unity Editor import; see docs/dummy-animation-art.md.";
        EditorUtility.SetDirty(catalog);
        AssetDatabase.SaveAssets();
        WriteReport(art, frames);
        Debug.Log("Monster Pouch: Dummy authored Idle/Move/Attack/Death clips installed; no board, timing, stats or original assets changed.");
    }

    private static Sprite[] Sequence(Sprite[,] frames, int row, params int[] columns)
    {
        var result = new Sprite[columns.Length];
        for (int i = 0; i < columns.Length; i++) result[i] = frames[row, columns[i]];
        return result;
    }

    private static void WriteReport(UnitArt art, Sprite[,] frames)
    {
        var report = new StringBuilder("# Dummy animation import audit\n\nGenerated by MonsterPouchDummyArtSetup.Setup, not a claim of rendered gameplay verification.\n\n");
        report.AppendLine($"Source: `{SourcePath}` (generated RGB magenta export, unchanged). Runtime derivative: `{AtlasPath}` (RGBA created by Unity).\n");
        var texture = new Texture2D(2, 2, TextureFormat.RGBA32, false);
        try
        {
            ImageConversion.LoadImage(texture, File.ReadAllBytes(AtlasPath), false);
            int transparent = 0, opaque = 0, partial = 0;
            foreach (Color32 pixel in texture.GetPixels32())
            {
                if (pixel.a == 0) transparent++;
                else if (pixel.a == 255) opaque++;
                else partial++;
            }
            report.AppendLine($"Actual derivative: {texture.width} x {texture.height}; alpha=0: {transparent}; alpha=255: {opaque}; partial alpha: {partial}.\n");
        }
        finally { UnityEngine.Object.DestroyImmediate(texture); }
        report.AppendLine("| Direction | Source row | Mirror X | Idle | Move | Attack (contact index 1) | Death |\n| --- | --- | --- | --- | --- | --- | --- |");
        for (int d = 0; d < 8; d++)
            report.AppendLine($"| {(UnitFacing)d} | {SourceRows[d]} | {art.DirectionalAnimations[d].FlipX} | 0,1 | 2,3,4,3 | 5,6,7 | 8,9,10 |");
        report.AppendLine("\n| Row | Column | Sprite | Rect | Pivot pixels | PPU |\n| --- | --- | --- | --- | --- | --- |");
        for (int row = 0; row < frames.GetLength(0); row++)
        for (int col = 0; col < frames.GetLength(1); col++)
        {
            Sprite sprite = frames[row, col];
            report.AppendLine($"| {row} | {col} | {sprite.name} | {sprite.rect} | {sprite.pivot} | {sprite.pixelsPerUnit} |");
        }
        Directory.CreateDirectory("docs");
        File.WriteAllText("docs/dummy-animation-import-report.md", report.ToString(), new UTF8Encoding(false));
    }
}
